title: "Paper Project"
description: "Минималистичный тредовый журнал на Jekyll."
url: "https://demansh.github.io"
baseurl: "/paper"
image: /assets/images/android-chrome-512x512.png

lang: ru

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - node_modules/
  - README.md

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "thread"
