name: Daily NASA Post

on:
  schedule:
    - cron: '0 2 * * *' # 06:00 AM AMT (Erevan)
  workflow_dispatch: # Чтобы можно было запустить вручную кнопкой в GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run NASA script
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
        run: python update_nasa.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "Aleksey Demshin"
          git config --global user.email "demansh17@gmail.com"
          git add _posts/
          # Если изменений нет (например, запуск дважды в день), экшн не упадет с ошибкой
          git commit -m "Add NASA APOD post: $(date +'%Y-%m-%d')" || exit 0
          git push